services:
  postgres:
    image: postgres:15
    container_name: museum-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - museum_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: museum-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_TOMCAT_THREADS_MAX: ${TOMCAT_THREADS_MAX}
      SERVER_TOMCAT_THREADS_MIN_SPARE: ${TOMCAT_THREADS_MIN_SPARE}
      SPRING_JPA_SHOW_SQL: "false"
    ports:
      - "8080:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    extra_hosts:
      - "host.docker.internal:host-gateway"

  statistics-service:
    build: ./museum-statistics-service
    container_name: statistics-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      MUSEUM_URL: http://museum-app:8080
    mem_limit: 512m
    cpus: 1

volumes:
  museum_data:
  db-data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge