apiVersion: apps/v1
kind: Deployment
metadata:
  name: museum-main
  namespace: var9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: museum-main
  template:
    metadata:
      labels:
        app: museum-main
    spec:
      containers:
      - name: museum-main
        image: fact154/main-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: museum-config
        - secretRef:
            name: db-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhub-secret 