apiVersion: v1
kind: Secret
metadata:
  name: museum-secrets
  namespace: var9
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: var9
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogIkZmQWNEVzFOYjNWeVltVkNaR05vYVc1blpYSWZkR1Z6ZER3Z1ptOXlaeTlrWVc1amIyMHZiblJsY2c9PSJ9fX0=
