apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Эти значения нужно заменить на base64-закодированные реальные значения
  SPRING_DATASOURCE_PASSWORD: base64_encoded_db_password
  DOCKER_USERNAME: base64_encoded_docker_username
  DOCKER_PASSWORD: base64_encoded_docker_password 