server:
  port: 8081

spring:
  application:
    name: statistics-service
  jpa:
    enabled: false
  datasource:
    enabled: false
  flyway:
    enabled: false
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
  data:
    redis:
      host: redis-service.var9.svc.cluster.local
      port: 6379
      timeout: 5000
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

museum:
  url: ${MUSEUM_URL}

statistics:
  cache:
    ttl-seconds: 1800
