version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: museum-db
    restart: always
    environment:
      POSTGRES_DB: museum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - museum_data:/var/lib/postgresql/data

volumes:
  museum_data:
