version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: museum-db
    restart: always
    environment:
      POSTGRES_DB: museum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - museum_data:/var/lib/postgresql/data
    health-check:
      test: [ "CMD-SHELL", "pg_isready -U admin -d museum" ]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Укажите ваш email
      PGADMIN_DEFAULT_PASSWORD: secret          # Укажите ваш пароль
    ports:
      - "5050:80"
    depends_on:
       postgres:
        - condition: service_healthy  # Теперь `pgadmin` запустится только после готовности `postgres`


volumes:
  museum_data:
